// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package airpc

import (
	"context"

	"gateway/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatRequest  = pb.ChatRequest
	ChatResponse = pb.ChatResponse

	Airpc interface {
		Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (pb.Airpc_ChatClient, error)
	}

	defaultAirpc struct {
		cli zrpc.Client
	}
)

func NewAirpc(cli zrpc.Client) Airpc {
	return &defaultAirpc{
		cli: cli,
	}
}

func (m *defaultAirpc) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (pb.Airpc_ChatClient, error) {
	client := pb.NewAirpcClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}
