// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: service.proto

package server

import (
	"context"

	"ai/service-mcp/internal/logic"
	"ai/service-mcp/internal/svc"
	"ai/service-mcp/pb"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
