// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ai.proto

package server

import (
	"gateway/internal/logic"
	"gateway/internal/svc"
	"gateway/pb"
)

type AirpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAirpcServer
}

func NewAirpcServer(svcCtx *svc.ServiceContext) *AirpcServer {
	return &AirpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AirpcServer) Chat(in *pb.ChatRequest, stream pb.Airpc_ChatServer) error {
	l := logic.NewChatLogic(stream.Context(), s.svcCtx)
	return l.Chat(in, stream)
}
