// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: service.proto

package rpc

import (
	"context"

	"ai/service-mcp/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest  = pb.LoginRequest
	LoginResponse = pb.LoginResponse
	Response      = pb.Response

	Rpc interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewRpcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
