// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Airpc_Chat_FullMethodName = "/ai.airpc/Chat"
)

// AirpcClient is the client API for Airpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirpcClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
}

type airpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAirpcClient(cc grpc.ClientConnInterface) AirpcClient {
	return &airpcClient{cc}
}

func (c *airpcClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Airpc_ServiceDesc.Streams[0], Airpc_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Airpc_ChatClient = grpc.ServerStreamingClient[ChatResponse]

// AirpcServer is the server API for Airpc service.
// All implementations must embed UnimplementedAirpcServer
// for forward compatibility.
type AirpcServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	mustEmbedUnimplementedAirpcServer()
}

// UnimplementedAirpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAirpcServer struct{}

func (UnimplementedAirpcServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAirpcServer) mustEmbedUnimplementedAirpcServer() {}
func (UnimplementedAirpcServer) testEmbeddedByValue()               {}

// UnsafeAirpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirpcServer will
// result in compilation errors.
type UnsafeAirpcServer interface {
	mustEmbedUnimplementedAirpcServer()
}

func RegisterAirpcServer(s grpc.ServiceRegistrar, srv AirpcServer) {
	// If the following call panics, it indicates UnimplementedAirpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Airpc_ServiceDesc, srv)
}

func _Airpc_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AirpcServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Airpc_ChatServer = grpc.ServerStreamingServer[ChatResponse]

// Airpc_ServiceDesc is the grpc.ServiceDesc for Airpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Airpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.airpc",
	HandlerType: (*AirpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Airpc_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
